--- #YAML:1.0
name:                PAB3
version:             3.2
abstract:            PAB - Perl Application Builder
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Digest::MD5:                   0
    Storable:                      0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
